packages:
  - esm2-650M
  - esm2-150M
  - currab
  - vhhbert
  - h3berta
  - tcr-bert
  - peptideclm-2
  - ablang2
  - catalogue

catalog:
  'turbo': ^2.5.6
  '@changesets/cli': ^2.29.6
  '@platforma-sdk/package-builder': 3.0.1
